version: '3.4'
services:
    react-ngnix-app:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80
        environment:
            - CHOKIDAR_USEPOLLING=true